### PR TITLE
Fix time_group() to preserve index order

### LINKED ISSUE #22: time_group() reshuffles index
Currently `time_group()` shuffles the index due to sort operation, therefore group assignment may be incorrect.  See #19 for details.
```
library(tibbletime)
data(FANG)

tibbletime_solution <- FANG %>% as_tbl_time(index = date) %>% 
  time_summarise(period = "weekly", n_week=n())
head(tibbletime_solution)
# A time tibble: 6 x 2
# Index: date
#        date n_week
#*     <date>  <int>
#1 2013-01-17     12
#2 2013-01-30     20
#3 2013-02-05     20
#4 2013-02-11     20
#5 2013-02-15     20
#6 2013-02-28     20

library(lubridate)
library(dplyr)

lubridate_solution <- FANG %>% 
  group_by(isoyear(date), isoweek(date)) %>% 
  group_by(date=max(date)) %>% 
  summarise(n_week=n()) 
head(lubridate_solution)
# A tibble: 6 x 2
#        date n_week
#     <date>  <int>
#1 2013-01-04     12
#2 2013-01-11     20
#3 2013-01-18     20
#4 2013-01-25     16
#5 2013-02-01     20
#6 2013-02-08     20

all.equal(lubridate_solution, tibbletime_solution)
```
Generally speaking, I am skeptical to solution with vectors and especially vector names. Would you consider rewriting the whole thing with tibbles? Joins seem to be much more reliable than `match()` where you rely on first match only, or a name subsetting (as I do in this PR).

### PR DESCRIPTION
**Pull request by dmi3kno**
Closes #22

### CODE REVIEW

**Comment by DavisVaughan** [comment]
@dmi3kno, apologies for not responding to all of this. Been away from a computer all weekend.

Let me first off say that I really appreciate all of the interest in the package. It's great to have community support. 

Also, I like where your brain had been heading with using tibbles and `full_join`'s. That is definitely a tidy solution that works. __In fact, this is how I had designed the initial version of time_group()__. See an old commit [here](https://github.com/business-science/tibbletime/blob/a3fef28a38866e125ad2e2e229d2a3b83a72ebe8/R/time_group.R#L123). 

The downside of this (that i had to find out the hard way) is it's slow as mud on large datasets. That `full_join()` really hurts the speed. Sorting and merging vectors is much faster. Below are a few examples:

## Your branch

```r
# Initial packages needed
library(dplyr)

# Your branch - a good idea, but dplyr makes it slow
devtools::install_github("dmi3kno/tibbletime")
library(tibbletime)
data(FANG)

FANG <- as_tbl_time(FANG, date) %>%
  group_by(symbol)

microbenchmark::microbenchmark(
  time_group(FANG$date, 2~m)
)

# Unit: milliseconds
# expr      min       lq     mean   median       uq      max neval
# time_group(FANG$date, 2 ~ m) 15.12276 18.12044 19.94773 19.37091 21.72333 30.59009   100
```

That is bearable, but what about with large datasets?

```r
ex <- create_series(~2013, 4~s) # >7mil observations
microbenchmark::microbenchmark(
  time_group(ex$date, 2~m),
  times = 5)

# Unit: seconds
# expr      min       lq     mean
# time_group(ex$date, 2 ~ m) 17.01458 17.79894 17.86635
# median       uq      max neval
# 17.92668 18.03816 18.55339     5
```

Upwards of 20 seconds??? Ouch!

## Current version of tibbletime

```r

# Current release
install.packages("tibbletime")
library(tibbletime)
data(FANG)

FANG <- as_tbl_time(FANG, date) %>%
  group_by(symbol)

microbenchmark::microbenchmark(
  time_group(FANG$date, 2~m)
)

# Unit: milliseconds
# expr      min       lq     mean   median       uq      max
# time_group(FANG$date, 2 ~ m) 4.691207 5.298462 8.812368 5.734693 7.381464 180.5138
# neval
# 100

```

Already faster. 3x times. What about big datasets?

```r
ex <- create_series(~2013, 4~s)

microbenchmark::microbenchmark(
  time_group(ex$date, 2~m),
  times = 5)

# Unit: seconds
# expr      min       lq     mean   median      uq      max neval
# time_group(ex$date, 2 ~ m) 1.919602 1.933078 2.080433 1.937248 1.96906 2.643174     5
```
     
Woah. 2 seconds compared to 20 seconds? Hopefully that makes things clear. `dplyr` is great, but that `full_join` and manipulating data frames just kills you on the time.

## A local branch I haven't pushed

As a last example, I have a local branch with a more optimized `time_group()` function. Results with the large dataset above are giving results in the `800 millisecond` range. Not bad compared to 20 seconds from dplyr.

## Final thoughts

In closing, I want to say thanks again for looking into this and giving a lot of time towards it. However, hopefully the examples above show a compelling case of why I will not be accepting this pull request to use tibbles rather than vectors. It's just a matter of speed.

As to the actual github issues that were the incentive for this PR, I will answer them one by one after this. Most of the problem comes from 

1) not having a grouped data set

2) tibbletime is going to make the assumption that your dates are sorted. this comes from using vectors for speed (like the above example).

**Comment by dmi3kno** [comment]
Thanks for details explanations, @DavisVaughan. I understand and respect the performance concern. Very eager to see your optimized version.

The assumption of sorted index looks easy to assert inside `time_group()` by comparing index to sorted index and at least issuing a warning: "It looks like your index is not sorted", although the chance of being lucky is fairly slim.

The assumption of grouped data can be assured one level up, in `time_collapse()`. There you have a method for ungrouped tibble. You could check if tibble has columns besides index and return a warning (if not an error) that the time collapsing may not be meaningful.

Feel free to turn down the PR or let me know if I should do it.

**Comment by DavisVaughan** [comment]
_Very eager to see your optimized version._

I added a branch and pushed this. [here](https://github.com/business-science/tibbletime/commit/a2d6c3243bf1fd5679fcb234eca62aa70e943eff)

Feel free to try it out

**Comment by dmi3kno** [comment]
As I am thinking of sorting assumption, `base::merge` comes to mind. Do you remember that it used to sort the data before merging, so you always had to watch out (learned it hard time on Kaggle when doing cross-validation and the row order would change every time). Now, we could do the same, making a mandatory sort in `time_collapse()` (or even higher up) before grouping the periods. If you want to be super nice, you could think of storing the original order in `.order` variable and restoring (arranging by it) it before returning the `tbl_time` back to user.

**Pull request closed without merging**
