### PR TITLE
Updates for tidyr 1.0.0

### PR DESCRIPTION
**Pull request by DavisVaughan**
- Leave open until tidyr is on CRAN
- Bump tidyr version to 1.0.0
- Remove tidyr Remote

### CODE REVIEW

**Comment by mdancho84** [comment]
Just a heads up, anomalize updates for tidyr v1.0.0 will depend on tibbletime.

**Comment by DavisVaughan** [comment]
Sounds good. I'll try and get this out monday too.

**Comment by mdancho84** [comment]
Hey Davis,
Let me know if these are OK to merge. I want to get the submission process rolling because of anomalize - I only have until 9/27 for CRAN. And right now it breaks with tidyr 1.0.0. 

Let me know.
-Matt

**Comment by DavisVaughan** [comment]
On vacation till Sunday! Feel free to merge and submit to CRAN if that's allowed. Or ask them for an extension

**Pull request merged**
